from dataclasses import dataclass
from scramble.settings import Settings
from scramble.app.court_state import CourtState
from scramble.app.player_state import PlayerState
from scramble.app.round_tracker import RoundTracker
from scramble.solver import ScrambleSolver
from scramble.core import Round
from scramble.utils import Serializable


@dataclass()
class AppSession(Serializable):
    """
    Represents a session for the Scramble app.
    This class is used to manage the state of the application during a session.

    Attributes
    ----------
    settings : Settings
        The settings for the Scramble app.
    player_state : PlayerState
        The state of players in the Scramble app.
    court_state : CourtState
        The state of courts in the Scramble app.
    round_tracker : RoundTracker
        The round tracker for managing rounds played in the Scramble app.
    session_name : str
        The name of the session.
    """
    settings: Settings
    player_state: PlayerState
    court_state: CourtState
    round_tracker: RoundTracker
    session_name: str

    def __init__(self, settings: Settings, session_name: str):
        """
        Initializes the AppSession with the given settings.

        Parameters
        ----------
        settings : Settings
            The settings for the Scramble app.
        session_name : str
            The name of the session.
        """
        self.settings = settings
        self.player_state = PlayerState()
        self.court_state = CourtState()
        self.round_tracker = RoundTracker()

        self.session_name = session_name

    @classmethod
    def from_dict(cls, data: dict) -> "AppSession":
        settings = Settings.from_dict(data["settings"])
        session_name = data.get("session_name", "default_session")

        app_session = cls(settings, session_name)
        app_session.player_state = PlayerState.from_dict(data["player_state"])
        app_session.court_state = CourtState.from_dict(data["court_state"])
        app_session.round_tracker = RoundTracker.from_dict(data["round_tracker"])

        return app_session

    def to_dict(self) -> dict:
        return {
            "settings": self.settings,
            "player_state": self.player_state,
            "court_state": self.court_state,
            "round_tracker": self.round_tracker,
        }

    def clear(self):
        """
        Clears the session state, including player state, court state, and round tracker.
        """
        self.player_state.clear()
        self.court_state.clear()
        self.round_tracker.clear()

    def get_new_round(self):
        """
        Generates a new round based on the current player state, court state, and settings.

        Returns
        -------
        Round
            A new Round object generated by the ScrambleSolver.
        """
        solver = ScrambleSolver(
            active_players=self.player_state.active_list(),
            history=self.round_tracker.history_manager,
            courts=self.court_state.courts_list(),
            settings=self.settings,
        )
        game_round = solver.solve()
        return game_round

    def start_round(self, game_round: Round):
        """
        Starts a new round by adding it to the round tracker and updating player states.

        Parameters
        ----------
        game_round : Round
            The round to be started.
        """
        self.round_tracker.add_round(game_round)
